ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Dec_21_ASP_Bikes.Models;

namespace Dec_21_ASP_Bikes.Models
{
   // [MetadataType(typeof(Login))]
    public partial class Registration
    {
    }

    public class Login
    {
        

        [Required(ErrorMessage = "Please Provide Username", AllowEmptyStrings = false)]
        public string Username { get; set; }

        [Required(ErrorMessage = "Please provide password", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Password { get; set; }
    }
}

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Controllers/RequestCycleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dec_21_ASP_Bikes.Models;
using System.Data.Entity;
using System.Data.SqlClient;
using PagedList;

namespace Dec_21_ASP_Bikes.Controllers
{

    public class RequestCycleController : Controller
    {

        // GET: Cycle
        public ActionResult Index()
        {
            BikesEntities1 db = new BikesEntities1();
            List<CycleDetail> clist = db.CycleDetails.ToList();
            return View(clist);
        }


        //        public ActionResult RequestName(int id)
        //        {
        //            BikesEntities1 db = new BikesEntities1();
        //            // List<RequestCycle> crequest = db.RequestCycles.Where(s => s.CycleID == id).ToList();
        //            // List<RequestCycle> crequest = db.RequestCycles.Include(c=> c.CycleRequestedByUsers).Distinct().Where(s => s.CycleID == id).ToList();
        //            List<RequestCycle> crequest = db.RequestCycles.Where(s => s.CycleID == id).ToList();


        //            var query = (from r in db.RequestCycles
        //                         where !(from u in db.CycleRequestedByUsers
        //                                 select u.RequestID).Contains(r.RequestID)
        //                         select r).Distinct();
        //           // var rid = query.Select(q => q.RequestID == cid);
        //            return View();

        //}



        public ActionResult RequestName(int id, int? page)
        {
            BikesEntities1 db = new BikesEntities1();
            // List<RequestCycle> crequest = db.RequestCycles.Where(s => s.CycleID == id).ToList();
            // List<RequestCycle> crequest = db.RequestCycles.Include(c=> c.CycleRequestedByUsers).Distinct().Where(s => s.CycleID == id).ToList();
           // List<RequestCycle> crequest = db.RequestCycles.Where(s => s.RequestID == id).ToList();


            //var query = (from r in db.RequestCycles
            //             where !(from u in db.CycleRequestedByUsers
            //                     select u.RequestID).Contains(r.RequestID)
            //             select r).Distinct();
            //return View(query.ToList().ToPagedList(page ?? 1, 7));

            var query = (from r in db.RequestCycles
                         where !(from u in db.CycleRequestedByUsers
                                 select u.RequestID).Contains(r.RequestID)
                         select r).Distinct().Where(r=>r.CycleID == id);
            return View(query.ToList().ToPagedList(page ?? 1, 7));


        }




        //ViewBag.query = (from r in crequest
        //             where !(from u in db.CycleRequestedByUsers
        //                     select u.RequestID).Contains(r.RequestID)
        //             select r).Distinct();
        //if(ViewBag.query == null)
        //{
        //    return Content("Sorry. This 🚲 is currently ❌ available. Please cum back later or try another 🚲");

        //}
        //else
        //{
        //       return View(ViewBag.query);




        [HttpPost]
        public ActionResult RequestName(CycleRequestedByUser rbu)
        {
           // try
            //{
                BikesEntities1 db = new BikesEntities1();
               // List<RequestCycle> rc = db.rc.ToList();
              
                //////int rid = rbu.RequestID;
               // int cid = rbu.CycleID;
               // DateTime fd = rbu.FromDate;
              //  DateTime td = rbu.ToDate;

               // CycleRequestedByUser crbu = new CycleRequestedByUser();
               // crbu.RequestID = rbu.RequestID;
                //crbu.CycleID = rbu.CycleID;
                //crbu.FromDate = (DateTime)rbu.FromDate;
              //  crbu.ToDate = (DateTime)rbu.ToDate;

               //select and insert statement

                db.CycleRequestedByUsers.Add(rbu);
                db.SaveChanges();
          //  }
            //catch (Exception ex)
          //  {
                //throw ex;
            

            //int RequestedCycleFromViewID = crbu.RequestID;

            return View(rbu);
        }


      



        //HttpGet





        //Insert Cyclist that could be requested

        public ActionResult RequestCycle()

    {
        CycleDetail c1 = new CycleDetail();
        return View(c1);
    }


    [HttpPost]

    public ActionResult RequestCycle(CycleDetail model, HttpPostedFileBase image1)
    {
        //creating an object of the context class to save the file into database table.
        var db = new BikesEntities1();

        //check if the image1 (id or name) is not equal to null
        if (image1 != null)
        {
            //convert your image into binary format;

            model.CycleImage = new byte[image1.ContentLength];

            //inputstream is used to convert the actual data to binary format
            image1.InputStream.Read(model.CycleImage, 0, image1.ContentLength);


        }
        //save model into datacontext
        db.CycleDetails.Add(model);
        db.SaveChanges();
        return View(model);
    }

}
    }

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Controllers/TestController.cs
using Dec_21_ASP_Bikes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Dec_21_ASP_Bikes.ViewModel;
using System.Net;
using System.Web.Security;

namespace Dec_21_ASP_Bikes.Controllers
{
    public class TestController : Controller
    {
        //  // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        //HttpGet
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(RequestCycle reg)
        {
            if (ModelState.IsValid)
            {
                BikesEntities1 db = new BikesEntities1();
                db.RequestCycles.Add(reg);
                db.SaveChanges();
                ModelState.Clear();
                reg = null;
                ViewBag.SuccessRegistration = "Registration was successfull";
            }
            return View();
        }



        public ActionResult TestRequestCycle(int id)
        {
            var rc = new List<RequestCycle>();
            var crbu = new List<CycleRequestedByUser>();
            // {
            // new CycleRequestedByUser {RequestID = 21 },
            //new CycleRequestedByUser {CycleID = 37 },
            // new CycleRequestedByUser { FromDate = DateTime ' 03/27/2015 12:00:00') },
            //  new CycleRequestedByUser {ToDate =  
            // };

            var vm = new MixOfRequestCycleNUserRequestViewModel
            {
                //rc = rc,
                //crbu = crbu

            };

            return View(vm);
        }



        public ActionResult RegisterCycleUser(int id)
        {

            BikesEntities1 db = new BikesEntities1();
            List<CycleRequestedByUser> crequest = db.CycleRequestedByUsers.Where(s => s.RequestID == id).ToList();

            return View(crequest);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterCycle(CycleRequestedByUser U)
        {
            if (ModelState.IsValid)
            {
                using (BikesEntities1 db = new BikesEntities1())
                {
                    //you should check duplicate registration here 
                    db.CycleRequestedByUsers.Add(U);
                    db.SaveChanges();
                    ModelState.Clear();
                    U = null;
                    ViewBag.registrationSuccess = "Registration was Successfull. Welcome ";
                    // return RedirectToAction("Index", "Home");
                }
            }
            return View(U);
        }

        public ActionResult Details(int? id)
        {
            BikesEntities1 db = new BikesEntities1();

            //We need a single cycle out of the list where the ID of the Cycle should be equal to the ID that we are passing into the dEtails action method

            RequestCycle singleCycleDetails = db.RequestCycles.Single(c => c.RequestID == id);
            return View(singleCycleDetails);

        }

        private BikesEntities1 db = new BikesEntities1();

        public ViewResult Index2(int id)
        {

            var courses = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Single(c => c.RequestID == id);
            //ViewBag.dropdownlist = new SelectList(d);
            //ViewBag.dropdownlist = new SelectList(db.RequestCycles, "RequestID", "RequestID");
            //RequestCycle rc = db.RequestCycles.Single(c => c.RequestID == id);
            return View(courses);
        }

        [HttpPost]
        public ActionResult Index1(CycleRequestedByUser crbu)
        {
            if (ModelState.IsValid)
            {
                db.CycleRequestedByUsers.Add(crbu);
                //db.Entry(crbu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DisplayImage", "Image");
            }
            //ViewBag.dropdownlist = new SelectList(db.CycleDetails, "CycleID", "CycleID");
            return View(crbu);
        }

        public ViewResult Index3(int id)
        {

            var courses = db.RequestCycles.Include(c => c.CycleDetail).Single(c => c.RequestID == id);
            //ViewBag.dropdownlist = new SelectList(d);
            //ViewBag.dropdownlist = new SelectList(db.RequestCycles, "RequestID", "RequestID");
            //RequestCycle rc = db.RequestCycles.Single(c => c.RequestID == id);
            return View(courses);
        }


        [HttpPost]
        public ActionResult Index3(RequestCycle rbu)
        {
            BikesEntities1 db = new BikesEntities1();
            List<RequestCycle> rc = db.RequestCycles.ToList();

            int rid = rbu.RequestID;
            int cid = rbu.CycleID;
            DateTime fd = rbu.FromDate;
            DateTime td = rbu.ToDate;

            CycleRequestedByUser crbu = new CycleRequestedByUser();

            crbu.RequestID = rbu.RequestID;
            crbu.CycleID = rbu.CycleID;
            crbu.FromDate = (DateTime)rbu.FromDate;
            crbu.ToDate = (DateTime)rbu.ToDate;

            //select and insert statement

            db.CycleRequestedByUsers.Add(crbu);
            db.SaveChanges();

            return View();


        }



        public ActionResult NavigateToRequestPage1(int id)
        {
            ViewBag.dropdownlist = new SelectList(db.RequestCycles, "CycleID", "CycleID");
            ViewBag.dropdownlist = new SelectList(db.RequestCycles, "RequestID", "RequestID");
            //RequestCycle singleCycleDetails = db.RequestCycles.Single(c => c.RequestID == id);
            //var rc = db.RequestCycles.Include(c=> c.Registration);
            return View();

        }

        [HttpPost]
        public ActionResult NavigateToRequestPage(CycleRequestedByUser crbu)
        {
            if (ModelState.IsValid)
            {
                db.CycleRequestedByUsers.Add(crbu);
                db.SaveChanges();
                return RedirectToAction("DisplayImage", "Image");
            }
            //ViewBag.dropdownlist = new SelectList(db.CycleDetails, "CycleID", "CycleID");
            return View(crbu);
        }

        public ViewResult DD(int id)
        {

            var userRequest = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Single(c => c.RequestID == id);
            Session["ViewUsername"] = db.Registrations.Single(c => c.Username == User.Identity.Name);
            Session["ViewRequest"] = userRequest;

            return View(userRequest);

        }


        [HttpPost]

        public ActionResult DD()
        {
            var ddreq = Session["ViewRequest"];
            var userddreq = Session["ViewUsername"];

            BikesEntities1 be = new BikesEntities1();
            //using (var be = new BikesEntities())
            //{
            //var x = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Single(c => c.RequestID == id);

            //foreach (var mystep in ddreq)
            //var mystep = be.RequestCycles.Where(p => p.RequestID == id).FirstOrDefault();

            //{
            CycleRequestedByUser task = new CycleRequestedByUser();

            task.RequestID = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).RequestID;
            task.CycleID = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).CycleID;
            task.FromDate = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).FromDate;
            task.ToDate = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).ToDate;
            task.Username = ((Dec_21_ASP_Bikes.Models.Registration)userddreq).Username;

            be.CycleRequestedByUsers.Add(task);
            //}
            be.SaveChanges();
            return View();

            //}
        }

        //public ViewResult UserProfileWithCycleDetails()
        //{

        //    //TestViewModel db = new TestViewModel();
        //        var userRequest1 = db.CycleRequestedByUsers.Include(c => c.Registration).Single(c => c.Username == User.Identity.Name);
        //    //var userRequest2 = db.Registrations.Single(c => c.Username == User.Identity.Name);
        //        Session["ViewRequest"] = userRequest1;
        //       // Session["ViewUsername"] = userRequest2;
        //        return View(userRequest1);



        //    }
        public ViewResult UserProfileWithCycleDetails()
        {


            try
            {


                //ViewBag.userRequest1 = db.CycleRequestedByUsers.Include(c => c.Registration).Single(c => c.Username == User.Identity.Name) ;
                ViewBag.userRequest1 = db.CycleRequestedByUsers.Where(a => a.Username == User.Identity.Name).OrderByDescending(x => x.UserRequest).Take(1).Single();
                //var userRequest2 = db.Registrations.Single(c => c.Username == User.Identity.Name);
                //  Session["ViewRequest"] = userRequest1;
                // Session["ViewUsername"] = userRequest2;


                return View(ViewBag.userRequest1);

            }
            catch (Exception)
            {
                ViewBag.Error = "Email cannot be sent. Please check the error and try again";
            }
            return View();

        }

        public ActionResult TestingUniqueRequestID(int id)
        {
            BikesEntities1 db = new BikesEntities1();
            //List<RequestCycle> crequest = db.RequestCycles.Where(s => s.RequestID == id).ToList();
            // List<RequestCycle> crequest = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Where(s => s.CycleID == id).ToList();


            //var query = db.RequestCycles.Join <RequestCycle, CycleRequestedByUser, int, RequestCycle>
            //    ( db.CycleRequestedByUsers, a => a.RequestID, b => b.RequestID,(a, b) => a).ToList();


            //ViewBag.towns = new SelectList(towns.Where(x => x.Name == x.Name.Distinct()).ToList(), "Value", "Text");

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/CycleBorrowed.cshtml
@model Dec_21_ASP_Bikes.Models.CycleRequestedByUser


@using (Html.BeginForm())
{

    <div>
        <h4>CycleRequestedByUser</h4>

       
            <h2>@ViewBag.Error</h2>
        



            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.CycleID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.CycleID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.FromDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FromDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ToDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ToDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Registration.Username)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Registration.Username)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Registration.Fullname)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Registration.Fullname)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RequestID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.RequestID)
                </dd>

            </dl>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Return Cycle" class="btn btn-default" />
                </div>
            </div>

        }





    </div>


}









@*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.UserRequest }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/DD.cshtml
@model Dec_21_ASP_Bikes.Models.RequestCycle

@using (Html.BeginForm("DD", "Test", FormMethod.Post))
{

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RequestID)
        </th>
		<th>
			@Html.DisplayNameFor(model => model.CycleID)
		</th>
        
       
    </tr>

    <tr>
        <td>
            @Html.DisplayFor(modelItem => Model.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.ToDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.RequestID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => Model.CycleID)
        </td>
        
    </tr>


</table>

<div class="form-group">
	<div class="col-md-offset-2 col-md-10">
		<input type="submit" value="Create" class="btn btn-default" />
	</div>
</div>
}

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/Details.cshtml
@model Dec_21_ASP_Bikes.Models.RequestCycle

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h2>Details</h2>

<div>
    <h4>CycleDetail</h4>
    <hr />

    <div style="border: solid; width: 400px;">
        <dl class="dl-horizontal">
            

          

            
            

            <dt>
                @Html.DisplayNameFor(model => model.RequestID)
            </dt>

            <dd style="border:double; width: 90px; text-align: center">
                @Html.DisplayFor(model => model.RequestID)
            </dd>

            <br />

            <dt>
                @Html.DisplayNameFor(model => model.CycleID)
            </dt>

            <dd style="border:double; width: 90px; text-align: center">
                @Html.DisplayFor(model => model.CycleID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FromDate)
            </dt>

            <dd style="border:double; width: 90px; text-align: center">
                @Html.DisplayFor(model => model.FromDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ToDate)
            </dt>

            <dd style="border:double; width: 90px; text-align: center">
                @Html.DisplayFor(model => model.ToDate)
            </dd>

        </dl>
    </div>

</div>
<br />

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Request Cycle" class="btn btn-default" />
    </div>
</div>

<p>

    @Html.ActionLink("Back to List", "CycleList", "CycleDetailsList")
</p>

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/DisableAccount.cshtml
@model Dec_21_ASP_Bikes.Models.Registration


@if (ViewBag.NotifyUser !=null)
{
    @ViewBag.NotifyUser;
}

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/DisplayDetails.cshtml
@model IEnumerable<Dec_21_ASP_Bikes.ViewModel.ProfileDetailsAndRequestedCycleDetails>

<table>
	<tr>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(m => item.CycleRequestedByUsers)
				@Html.DisplayFor(m => item.Registrations)
			</td>
			s
			<td>
				@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
				@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
				@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
			</td>

		</tr>
	}

</table>

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/FinalDeactivationCheck.cshtml
@model Dec_21_ASP_Bikes.Models.CycleRequestedByUser

@if(ViewBag.NotifyUser != null)
{
    @ViewBag.NotifyUser
}

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/Index1.cshtml
@model Dec_21_ASP_Bikes.Models.RequestCycle

@{
	ViewBag.Title = "UserProfile";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test REquested Cycles</h2>

<p>
	@Html.ActionLink("Create New", "Create")
</p>
<table>
	<tr>
		<th></th>
		<th>Request ID</th>
		<th>Cycle ID</th>
		<th>From Date</th>
		<th>To Date</th>
	</tr>

	
		<tr>
			<td>
				@Html.ActionLink("Edit", "Edit", new { id = Model.RequestID  }) |
				
			</td>
			<td>
				@Html.DisplayFor(modelItem => Model.RequestID)
			</td>
			<td>
				@Html.DisplayFor(modelItem => Model.CycleID)
			</td>
			<td>
				@Html.DisplayFor(modelItem => Model.FromDate)
			</td>
			<td>
				@Html.DisplayFor(modelItem => Model.ToDate)
			</td>

			<td>
				@Html.DisplayFor(modelItem => Model.CycleDetail.CycleType)
			</td>


			
		</tr>
	
</table>

<a href="@Url.Action("Index1", "Test", new { id = Model.RequestID })">Request Me</a>)

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/Login.cshtml
@model Dec_21_ASP_Bikes.ViewModel.DeactivationWithLoginViewModel

@{
    ViewBag.Title = "Login";

}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/jquery-1.12.4.js"></script>
<link href="~/Content/Login.css" rel="stylesheet" />


<h2>Login</h2>

@using (Html.BeginForm("Login", "Test", FormMethod.Post))

{

    if (ViewBag.NotifyUser != null)
    {

        <h4> @ViewBag.NotifyUser</h4>
        <p>@ViewBag.SendEmail</p>

    }
    else
    {
        @Html.AntiForgeryToken()

        <div style="background-image:url('/Content/Images/AboutUcm.jpg'); background-size: 400px 200px;">


            <div class="form-horizontal">
                <h4>Login User</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })

                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Login" class="btn btn-default" />
                        <input type="button" value="Cancel" class="btn btn-default"
                               onclick="javascript:document.location.href='@Url.Action("Login", "Test")'" />
                    </div>
                </div>
            </div>
        </div>
    }
}

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/Test/RegisterCycle.cshtml
@model IEnumerable<Dec_21_ASP_Bikes.Models.RequestCycle>




@{
    ViewBag.Title = "Requested Bicycle";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var grid = new WebGrid(source: Model, canPage: true);
    grid.Pager(WebGridPagerModes.All);
}

<h2>Details of Requested Bicycle</h2>
<br />

<h2>Login</h2>

@using (Html.BeginForm())

{
    @Html.AntiForgeryToken()


    @grid.GetHtml(
                    tableStyle: "webgrid-table",
                    headerStyle: "webgrid-header",
                    footerStyle: "webgrid-footer",
                    alternatingRowStyle: "webgrid-alternating-row",
                    rowStyle: "webgrid-row-style",
                    columns: grid.Columns(
                        //here i will add column for serial no
                        grid.Column(header: "Serial No", format:@<text><div>@(item.WebGrid.Rows.IndexOf(item) + 1)</div></text>),
                        //grid.Column(columnName: "CycleAccessories", header: "Accessories"),
                        // grid.Column(columnName: "CycleType", header: "Type"),
                        grid.Column(columnName: "RequestID", header: "RequestID"),
                        grid.Column(columnName: "CycleID", header: "CycleID"),
                        grid.Column(columnName: "FromDate", header: "Start Date"),
                        grid.Column(columnName: "ToDate", header: "End Date")
                    //  grid.Column(columnName: "CycleImage", header: "Image", format:

                    //grid.Column("", header: "Request Cycle", format: @<a href="@Url.Action("RegisterCycle", "RequestCycle", new { id = item.CycleID })">Request Me</a>)
                   
    

                          ))


}

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Create" class="btn btn-default" />
    </div>
</div>
    