ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Controllers/SendEmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Dec_21_ASP_Bikes.Controllers
{

  
    public class SendEmailController : Controller
    {
        // GET: SendEmail
        public ActionResult Form()
        {
            return View();
        }

        [HttpPost]

        public ActionResult Form(string ReceiverEmail, string Subject, string Message)
        {
            try
            {

                if (ModelState.IsValid)
                {

                  var senderEmail = new MailAddress("asp.a@mail.com", "UCM Bikes");
                    var receiverEmail = new MailAddress(ReceiverEmail, "Receiver");

                    var password = "Testing786";
                    var sub = "Reminder from UCM Bikes";
                    var body = "Hello... Your time to return the cycle has exceeded";

                    var smtp = new SmtpClient
                    {
                        Host = "smtp.mail.com",
                        Port = 587,
                        EnableSsl = true,
                        DeliveryMethod = SmtpDeliveryMethod.Network,
                        UseDefaultCredentials = false,
                        Credentials = new NetworkCredential(senderEmail.Address, password)
                    };

                    using (var New_message = new MailMessage(senderEmail, receiverEmail)
                    {
                        Subject = sub,
                        Body = body
                    }
                    )
                    {
                        smtp.Send(New_message);
                        ViewBag.SuccessMail = "Email has been sent successfully.";


                    }

                    return View();
                } //End Of If(ModelStste.IsValid)

            } //End of try

            catch (Exception)
            {
                ViewBag.Error = "Email cannot be sent. Please check the error and try again";
            }

            return View();
        }
    }
}

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/SendEmail/Form.cshtml
@{
    ViewBag.Title = "Email Student";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Send a Reminder mail to the student</h2>


<br />
<br />

@if (ViewBag.Error != null)
{
    <h2>@ViewBag.Error</h2>
}
else
{
    <h2>@ViewBag.SuccessMail</h2>
}

<div>
    <form method="post" action="Form">
        <span class="form-control-static">Receiver Email: </span>
        <input class="form-control" type="text" name="ReceiverEmail" />

        @*<span class="form-control-static">Subject: </span>
        <input class="form-control" type="text" name="sub" />

        <span class="form-control-static"> Message: </span>*@
        @*<input class="form-control" type="text" name="body" />*@
        <br />

        <button class="btn btn-primary" type="submit">Send Email</button>
        <input class="btn btn-primary"  type="button" value="Cancel"
               onclick="javascript:document.location.href='@Url.Action("Form", "SendEmail")'" />
    </form>
</div>