ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Models/CycleRequestedByUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dec_21_ASP_Bikes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycleRequestedByUser
    {
        public int UserRequest { get; set; }
        public int RequestID { get; set; }
        public int CycleID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Username { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
    
        public virtual RequestCycle RequestCycle { get; set; }
        public virtual Registration Registration { get; set; }
    }
}

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Controllers/CycleRequestedByUserController.cs
using Dec_21_ASP_Bikes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Dec_21_ASP_Bikes.Controllers
{
	public class CycleRequestedByUserController : Controller
	{
		// GET: CycleRequestedByUser

		private BikesEntities1 db = new BikesEntities1();

		public ActionResult Index()
		{
			return View();
		}


		//Get Method: User requestes the Cycle by Clciking on the REquest Me link in the Cycle details page.

		public ActionResult NavigateToRequestPage()
		{
			ViewBag.dropdownlist = new SelectList(db.RequestCycles, "CycleID", "CycleID");
			ViewBag.dropdownlist = new SelectList(db.RequestCycles, "RequestID", "RequestID");
			
			//RequestCycle rc = db.RequestCycles.Single(c => c.RequestID == id);
			return View();

		}

		[HttpPost]
		public ActionResult NavigateToRequestPage(CycleRequestedByUser crbu)
		{
			if (ModelState.IsValid)
			{
				db.CycleRequestedByUsers.Add(crbu);
				db.SaveChanges();
				return RedirectToAction("DisplayImage", "Image");
			}
			//ViewBag.dropdownlist = new SelectList(db.CycleDetails, "CycleID", "CycleID");
			return View(crbu);
		}


		public ActionResult DisplayRequestedDetails1(int id)
		{

			var userRequest = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Single(c => c.RequestID == id);
            Session["ViewUsername"] = db.Registrations.Single(c => c.Username == User.Identity.Name);
            Session["ViewRequest"] = userRequest;
            return View(userRequest);

		}


		[HttpPost]

		public ActionResult DisplayRequestedDetails1()
		{
			var ddreq = Session["ViewRequest"];
            var userddreq = Session["ViewUsername"];
            BikesEntities1 be = new BikesEntities1();
			//using (var be = new BikesEntities())
			//{
			//var x = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Single(c => c.RequestID == id);

			//foreach (var mystep in ddreq)
			//var mystep = be.RequestCycles.Where(p => p.RequestID == id).FirstOrDefault();

			//{

           // var currentDate = DateTime.Now;
			CycleRequestedByUser task = new CycleRequestedByUser();
            RequestCycle rc = new RequestCycle();

            //var checkDateWithDate = DateTime.Now.AddDays(7);


            task.RequestID = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).RequestID;
			task.CycleID = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).CycleID;
			task.FromDate = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).FromDate;
			task.ToDate = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).ToDate;

            var ToDateWithDate = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).ToDate;


            task.Username = ((Dec_21_ASP_Bikes.Models.Registration)userddreq).Username;
            task.CheckDate = ToDateWithDate.AddDays(7);

            if (task.Username != null)
            {
                task.Status = true;
                rc.Status = true;
            }

            else
            {
                task.Status = false;
                rc.Status = false;
            }

            be.CycleRequestedByUsers.Add(task);

            

            db.Entry(rc).State = EntityState.Modified;

           // db.SaveChanges();


            //}
            be.SaveChanges();
            //db.SaveChanges();

            ViewBag.InsertedDataToTable4 = "Congtaz 👍👍👍👍" + User.Identity.Name + ". Your 🚲 request was successfull";
            ViewBag.navigationToCyclesBorrowed = "🚲";





            return View();

			//}
		}






        public ViewResult UserProfileWithCycleDetails()
        {

            //TestViewModel db = new TestViewModel();
            try
            {


                //  ViewBag.userRequest1 = db.CycleRequestedByUsers.Include(c => c.Registration).Single(c => c.Username == User.Identity.Name);
                ViewBag.userRequest1 = db.CycleRequestedByUsers.Where(a => a.Username == User.Identity.Name).OrderByDescending(x => x.UserRequest).Take(1).Single();

                //var userRequest2 = db.Registrations.Single(c => c.Username == User.Identity.Name);
                //  Session["ViewRequest"] = userRequest1;
                // Session["ViewUsername"] = userRequest2;


                return View(ViewBag.userRequest1);
                
            }
            catch (Exception)
            {
                ViewBag.Error = "Email cannot be sent. Please check the error and try again";
            }
            return View();



        }




        //[HttpPost]

        //public ViewResult UserProfileWithCycleDetails(CycleRequestedByUser cbru, int id)
        //{
        //    // var ddreq = Session["ViewRequest"];
        //    //var ddreq = Session["ViewRequest"];
        //    BikesEntities1 db = new BikesEntities1();

        //    //CycleRequestedByUser task = new CycleRequestedByUser();

        //    var updateStatus = db.CycleRequestedByUsers.SingleOrDefault(w => w.RequestID == id);
        //    updateStatus.Status = false;

        //    db.SaveChanges();
        //    return View();

    }
}


   








       


   

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Controllers/TestController.cs
using Dec_21_ASP_Bikes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Dec_21_ASP_Bikes.ViewModel;
using System.Net;
using System.Web.Security;

namespace Dec_21_ASP_Bikes.Controllers
{
    public class TestController : Controller
    {
        //  // GET: Account
        public ActionResult Index()
        {
            return View();
        }

        //HttpGet
        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(RequestCycle reg)
        {
            if (ModelState.IsValid)
            {
                BikesEntities1 db = new BikesEntities1();
                db.RequestCycles.Add(reg);
                db.SaveChanges();
                ModelState.Clear();
                reg = null;
                ViewBag.SuccessRegistration = "Registration was successfull";
            }
            return View();
        }



        public ActionResult TestRequestCycle(int id)
        {
            var rc = new List<RequestCycle>();
            var crbu = new List<CycleRequestedByUser>();
            // {
            // new CycleRequestedByUser {RequestID = 21 },
            //new CycleRequestedByUser {CycleID = 37 },
            // new CycleRequestedByUser { FromDate = DateTime ' 03/27/2015 12:00:00') },
            //  new CycleRequestedByUser {ToDate =  
            // };

            var vm = new MixOfRequestCycleNUserRequestViewModel
            {
                //rc = rc,
                //crbu = crbu

            };

            return View(vm);
        }



        public ActionResult RegisterCycleUser(int id)
        {

            BikesEntities1 db = new BikesEntities1();
            List<CycleRequestedByUser> crequest = db.CycleRequestedByUsers.Where(s => s.RequestID == id).ToList();

            return View(crequest);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterCycle(CycleRequestedByUser U)
        {
            if (ModelState.IsValid)
            {
                using (BikesEntities1 db = new BikesEntities1())
                {
                    //you should check duplicate registration here 
                    db.CycleRequestedByUsers.Add(U);
                    db.SaveChanges();
                    ModelState.Clear();
                    U = null;
                    ViewBag.registrationSuccess = "Registration was Successfull. Welcome ";
                    // return RedirectToAction("Index", "Home");
                }
            }
            return View(U);
        }

        public ActionResult Details(int? id)
        {
            BikesEntities1 db = new BikesEntities1();

            //We need a single cycle out of the list where the ID of the Cycle should be equal to the ID that we are passing into the dEtails action method

            RequestCycle singleCycleDetails = db.RequestCycles.Single(c => c.RequestID == id);
            return View(singleCycleDetails);

        }

        private BikesEntities1 db = new BikesEntities1();

        public ViewResult Index2(int id)
        {

            var courses = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Single(c => c.RequestID == id);
            //ViewBag.dropdownlist = new SelectList(d);
            //ViewBag.dropdownlist = new SelectList(db.RequestCycles, "RequestID", "RequestID");
            //RequestCycle rc = db.RequestCycles.Single(c => c.RequestID == id);
            return View(courses);
        }

        [HttpPost]
        public ActionResult Index1(CycleRequestedByUser crbu)
        {
            if (ModelState.IsValid)
            {
                db.CycleRequestedByUsers.Add(crbu);
                //db.Entry(crbu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("DisplayImage", "Image");
            }
            //ViewBag.dropdownlist = new SelectList(db.CycleDetails, "CycleID", "CycleID");
            return View(crbu);
        }

        public ViewResult Index3(int id)
        {

            var courses = db.RequestCycles.Include(c => c.CycleDetail).Single(c => c.RequestID == id);
            //ViewBag.dropdownlist = new SelectList(d);
            //ViewBag.dropdownlist = new SelectList(db.RequestCycles, "RequestID", "RequestID");
            //RequestCycle rc = db.RequestCycles.Single(c => c.RequestID == id);
            return View(courses);
        }


        [HttpPost]
        public ActionResult Index3(RequestCycle rbu)
        {
            BikesEntities1 db = new BikesEntities1();
            List<RequestCycle> rc = db.RequestCycles.ToList();

            int rid = rbu.RequestID;
            int cid = rbu.CycleID;
            DateTime fd = rbu.FromDate;
            DateTime td = rbu.ToDate;

            CycleRequestedByUser crbu = new CycleRequestedByUser();

            crbu.RequestID = rbu.RequestID;
            crbu.CycleID = rbu.CycleID;
            crbu.FromDate = (DateTime)rbu.FromDate;
            crbu.ToDate = (DateTime)rbu.ToDate;

            //select and insert statement

            db.CycleRequestedByUsers.Add(crbu);
            db.SaveChanges();

            return View();


        }



        public ActionResult NavigateToRequestPage1(int id)
        {
            ViewBag.dropdownlist = new SelectList(db.RequestCycles, "CycleID", "CycleID");
            ViewBag.dropdownlist = new SelectList(db.RequestCycles, "RequestID", "RequestID");
            //RequestCycle singleCycleDetails = db.RequestCycles.Single(c => c.RequestID == id);
            //var rc = db.RequestCycles.Include(c=> c.Registration);
            return View();

        }

        [HttpPost]
        public ActionResult NavigateToRequestPage(CycleRequestedByUser crbu)
        {
            if (ModelState.IsValid)
            {
                db.CycleRequestedByUsers.Add(crbu);
                db.SaveChanges();
                return RedirectToAction("DisplayImage", "Image");
            }
            //ViewBag.dropdownlist = new SelectList(db.CycleDetails, "CycleID", "CycleID");
            return View(crbu);
        }

        public ViewResult DD(int id)
        {

            var userRequest = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Single(c => c.RequestID == id);
            Session["ViewUsername"] = db.Registrations.Single(c => c.Username == User.Identity.Name);
            Session["ViewRequest"] = userRequest;

            return View(userRequest);

        }


        [HttpPost]

        public ActionResult DD()
        {
            var ddreq = Session["ViewRequest"];
            var userddreq = Session["ViewUsername"];

            BikesEntities1 be = new BikesEntities1();
            //using (var be = new BikesEntities())
            //{
            //var x = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Single(c => c.RequestID == id);

            //foreach (var mystep in ddreq)
            //var mystep = be.RequestCycles.Where(p => p.RequestID == id).FirstOrDefault();

            //{
            CycleRequestedByUser task = new CycleRequestedByUser();

            task.RequestID = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).RequestID;
            task.CycleID = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).CycleID;
            task.FromDate = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).FromDate;
            task.ToDate = ((Dec_21_ASP_Bikes.Models.RequestCycle)ddreq).ToDate;
            task.Username = ((Dec_21_ASP_Bikes.Models.Registration)userddreq).Username;

            be.CycleRequestedByUsers.Add(task);
            //}
            be.SaveChanges();
            return View();

            //}
        }

        //public ViewResult UserProfileWithCycleDetails()
        //{

        //    //TestViewModel db = new TestViewModel();
        //        var userRequest1 = db.CycleRequestedByUsers.Include(c => c.Registration).Single(c => c.Username == User.Identity.Name);
        //    //var userRequest2 = db.Registrations.Single(c => c.Username == User.Identity.Name);
        //        Session["ViewRequest"] = userRequest1;
        //       // Session["ViewUsername"] = userRequest2;
        //        return View(userRequest1);



        //    }
        public ViewResult UserProfileWithCycleDetails()
        {


            try
            {


                //ViewBag.userRequest1 = db.CycleRequestedByUsers.Include(c => c.Registration).Single(c => c.Username == User.Identity.Name) ;
                ViewBag.userRequest1 = db.CycleRequestedByUsers.Where(a => a.Username == User.Identity.Name).OrderByDescending(x => x.UserRequest).Take(1).Single();
                //var userRequest2 = db.Registrations.Single(c => c.Username == User.Identity.Name);
                //  Session["ViewRequest"] = userRequest1;
                // Session["ViewUsername"] = userRequest2;


                return View(ViewBag.userRequest1);

            }
            catch (Exception)
            {
                ViewBag.Error = "Email cannot be sent. Please check the error and try again";
            }
            return View();

        }

        public ActionResult TestingUniqueRequestID(int id)
        {
            BikesEntities1 db = new BikesEntities1();
            //List<RequestCycle> crequest = db.RequestCycles.Where(s => s.RequestID == id).ToList();
            // List<RequestCycle> crequest = db.RequestCycles.Include(c => c.CycleRequestedByUsers).Where(s => s.CycleID == id).ToList();


            //var query = db.RequestCycles.Join <RequestCycle, CycleRequestedByUser, int, RequestCycle>
            //    ( db.CycleRequestedByUsers, a => a.RequestID, b => b.RequestID,(a, b) => a).ToList();


            //ViewBag.towns = new SelectList(towns.Where(x => x.Name == x.Name.Distinct()).ToList(), "Value", "Text");

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/CycleRequestedByUser/DisplayRequestedDetails.cshtml
@*@model Dec_21_ASP_Bikes.Models.RequestCycle

@using (Html.BeginForm("DisplayRequestedDetails", "CycleRequestedByUser", FormMethod.Post))
{

	<p>
		@Html.ActionLink("Create New", "Create")
	</p>
	<table class="table">
		<tr>
			<th>
				@Html.DisplayNameFor(model => model.FromDate)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.ToDate)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.RequestID)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.CycleID)
			</th>


		</tr>

		<tr>
			<td>
				@Html.DisplayFor(modelItem => Model.FromDate)
			</td>
			<td>
				@Html.DisplayFor(modelItem => Model.ToDate)
			</td>
			<td>
				@Html.DisplayFor(modelItem => Model.RequestID)
			</td>
			<td>
				@Html.DisplayFor(modelItem => Model.CycleID)
			</td>

		</tr>


	</table>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Create" class="btn btn-default" />
		</div>
	</div>
}*@

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/CycleRequestedByUser/DisplayRequestedDetails1.cshtml
@model Dec_21_ASP_Bikes.Models.RequestCycle

@using (Html.BeginForm("DisplayRequestedDetails1", "CycleRequestedByUser", FormMethod.Post))
{

    if (ViewBag.InsertedDataToTable4 != null)
    {
        <h2>@ViewBag.InsertedDataToTable4</h2>

        <h3>@Html.ActionLink("Click me to check " + (string)ViewBag.navigationToCyclesBorrowed + " borrowed", "UserProfileWithCycleDetails1", "EligibilityAndUserProfile")</h3>
    }

     else
         {

        <div>
            <h4>RequestCycle</h4>
            <hr />
            <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.FromDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FromDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToDate)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.CycleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CycleID)
        </dd>


    </dl>

</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Borrow Me" class="btn btn-default" />
    </div>
</div>
    }



@*<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RequestID }) |
    @Html.ActionLink("Back to List", "Index")
</p>*@

}

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/CycleRequestedByUser/NavigateToRequestPage.cshtml
@model Dec_21_ASP_Bikes.Models.CycleRequestedByUser

@using (Html.BeginForm("NavigateToRequestPage", "CycleRequestedByUser", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CycleRequestedByUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RequestID, "RequestID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
				@Html.DropDownListFor(model => model.RequestID, (SelectList)ViewBag.dropdownlist, new { @class = "form-control" })


                @Html.ValidationMessageFor(model => model.RequestID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CycleID, "CycleID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               
                @Html.DropDownListFor(model => model.CycleID, (SelectList)ViewBag.dropdownlist, new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.CycleID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FromDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FromDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ASP_700646318/Dec 21_ASP_Bikes/Dec 21_ASP_Bikes/Views/CycleRequestedByUser/UserProfileWithCycleDetails.cshtml
@model Dec_21_ASP_Bikes.Models.CycleRequestedByUser


@using (Html.BeginForm("UserProfileWithCycleDetails", "CycleRequestedByUser", FormMethod.Post))
{

<div>
    <h4>CycleRequestedByUser</h4>

    @if (ViewBag.Error != null)
    {
        <h2>The user has no data to display</h2>
    }
    else

    {



        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CycleID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CycleID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FromDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FromDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ToDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ToDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Registration.Username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Registration.Username)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Registration.Fullname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Registration.Fullname)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RequestID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RequestID)
            </dd>

        </dl>

        @*@Html.ActionLink("Return Cycle", "ReturnCycle", "Test", new { id = Model.RequestID })*@
        <a href="@Url.Action("ReturnCycle", "Test", new { id = Model.RequestID })">Return Cycle</a>


    }

    

</div>
}



    


@*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.UserRequest }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@